apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goldengate_westcoast
    instance: goldengate_oracle_23.4.0
  name: goldengate-oracle-westcoast
  namespace: goldengate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goldengate_westcoast
      instance: goldengate_oracle_23.4.0
  template:
    metadata:
      labels:
        app: goldengate_westcoast
        instance: goldengate_oracle_23.4.0
    spec:
      containers:
      - env:
        - name: OGG_DEPLOYMENT
          value: WestCoastDeployment
        - name: OGG_ADMIN
          valueFrom:
            secretKeyRef:
              key: oggadmin
              name: ogg-admin-secret
        - name: OGG_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              key: oggadminpwd
              name: ogg-admin-secret
        image: fra.ocir.io/frul1g8cgfam/pub_gg_micro_ora:23.4.0
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 443
          name: ggate
          protocol: TCP
        volumeMounts:
        - mountPath: /u01/ogg/scripts
          name: u01
        - mountPath: /u02
          name: u02
        - mountPath: /u03
          name: u03
      volumes:
      - name: u01
        persistentVolumeClaim:
          claimName: ogg-oracle-westcoast-u01-pvc
      - name: u02
        persistentVolumeClaim:
          claimName: ogg-oracle-westcoast-u02-pvc
      - name: u03
        persistentVolumeClaim:
          claimName: ogg-oracle-westcoast-u03-pvc

