{
 "title": "GoldenGate Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values(process_performance_process_id,deploymentName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Replicats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total inserts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics_replicat_mapped_total_inserts{deploymentName=\"$deployment\", processType=\"replicat\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total deletes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics_replicat_mapped_total_deletes{deploymentName=\"$deployment\", processType=\"replicat\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total updates",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics_replicat_mapped_total_updates{deploymentName=\"$deployment\", processType=\"replicat\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mapped Table Updates",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "statistics_table_replicat_mapped_total_updates{deploymentName=\"$deployment\"}",
     "legendFormat": "{{target_table_name}}"
    }
   ]
  },
  {
   "title": "Mapped Table Inserts",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "statistics_table_replicat_mapped_total_inserts{deploymentName=\"$deployment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mapped Table deletes",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "statistics_table_replicat_mapped_total_deletes{deploymentName=\"$deployment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "position_er_high_watermark_lag{deploymentName=\"$deployment\", processType=\"replicat\"}",
     "legendFormat": "High Watermark lag for process {{processName}}"
    },
    {
     "expr": "position_er_low_watermark_lag{deploymentName=\"$deployment\", processType=\"replicat\"}",
     "legendFormat": "Low Watermark for process {{processName}}"
    },
    {
     "expr": "position_er_last_operation_lag{deploymentName=\"$deployment\", processType=\"replicat\"}",
     "legendFormat": "Last operatoin lag for process {{processName}}"
    }
   ]
  },
  { "title": "Extracts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total inserts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics_extract_mapped_total_inserts{deploymentName=\"$deployment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total deletes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics_extract_mapped_total_deletes{deploymentName=\"$deployment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total updates",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics_extract_mapped_total_updates{deploymentName=\"$deployment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extract Table Updates",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "statistics_table_extract_mapped_total_updates{deploymentName=\"$deployment\"}",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Extract Table Inserts",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "statistics_table_extract_mapped_total_inserts{deploymentName=\"$deployment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extract Table Deletes",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "statistics_table_extract_mapped_total_deletes{deploymentName=\"$deployment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "position_er_high_watermark_lag{deploymentName=\"$deployment\"}",
     "legendFormat": "High Watermark for process {{processName}}"
    },
    {
     "expr": "position_er_low_watermark_lag{deploymentName=\"$deployment\", processType=\"extract\"}",
     "legendFormat": "Low Watermark for process {{processName}}"
    },
    {
     "expr": "position_er_last_operation_lag{deploymentName=\"$deployment\", processType=\"extract\"}",
     "legendFormat": "Last Operation Lag for process {{processName}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Distribution and Receiver Service IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "receiver_service_stats_total_bytes_received{deploymentName=\"$deployment\"}",
     "legendFormat": "Receiver Bytes incoming for {{path_name}}"
    },
    {
     "expr": "receiver_service_stats_total_bytes_sent{deploymentName=\"$deployment\"}",
     "legendFormat": "Receiver Bytes outgoing  for {{path_name}}"
    },
    {
     "expr": "distributionServer_network_stats_total_bytes_sent{deploymentName=\"$deployment\"}",
     "legendFormat": "Distrubution Bytes outgoing for {{path_name}}"
    },
    {
     "expr": "distributionServer_network_stats_total_bytes_received{deploymentName=\"$deployment\"}",
     "legendFormat": "Distribution Bytes incoming for {{path_name}}"
    }
   ]
  }
 ]
}