apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ogg-oracle-eastcoast-u01-pvc
  namespace: goldengate
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ogg-oracle-eastcoast-u03-pvc
  namespace: goldengate
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ogg-oracle-eastcoast-u03-pvc
  namespace: goldengate
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-block
