apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: statsd-exporter
    app.kubernetes.io/name: statsd-exporter-prometheus
  name: statsd-exporter-prometheus
  namespace: goldengate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: statsd-exporter
      app.kubernetes.io/name: statsd-exporter-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: statsd-exporter
        app.kubernetes.io/name: statsd-exporter-prometheus
    spec:
      containers:
      - image: docker.io/prom/statsd-exporter:latest
        imagePullPolicy: Always
        args: ["--statsd.mapping-config", "/config/statsd-mapping.yaml", "--log.level", "debug"]
        name: app
        ports:
        - containerPort: 9102
          name: http
          protocol: TCP
        - containerPort: 9125
          name: push
          protocol: UDP
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: statsd-mapping-config

