apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: statsd-exporter
    app.kubernetes.io/name: statsd-exporter-prometheus-service
    app: gg23ai-east
  name: statsd-exporter-service
  namespace: goldengate
spec:
  ports:
  - port: 8125
    protocol: UDP
    targetPort: 9125
    name: push
  - port: 9102
    protocol: TCP
    targetPort: 9102
    name: http
  selector:
    app.kubernetes.io/instance: statsd-exporter
    app.kubernetes.io/name: statsd-exporter-prometheus
  type: ClusterIP

